-- migrate:up
CREATE TABLE IF NOT EXISTS user (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	name VARCHAR(30) NOT NULL UNIQUE,
	password BINARY(60) NOT NULL,
	level ENUM('banned', 'member', 'bot', 'moderator', 'admin') NOT NULL DEFAULT 'member',

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS post_crawl_info (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	site VARCHAR(255) NOT NULL,
	url VARCHAR(255) NOT NULL UNIQUE,
	data JSON NOT NULL,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
	CHECK(JSON_VALID(data))
);

CREATE TABLE IF NOT EXISTS post (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	source VARCHAR(255),
	uploader BIGINT UNSIGNED NOT NULL,

	hash CHAR(44) NOT NULL UNIQUE,

	crawl_info BIGINT UNSIGNED,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (uploader) REFERENCES user(id),
	FOREIGN KEY (crawl_info) REFERENCES post_crawl_info(id)
);

CREATE TABLE IF NOT EXISTS pool (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,

	owner BIGINT UNSIGNED NOT NULL,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (owner) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS pool_post (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	num INT UNSIGNED NOT NULL,

	post BIGINT UNSIGNED NOT NULL,
	pool BIGINT UNSIGNED NOT NULL,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,

	UNIQUE(post, pool),
	FOREIGN KEY (post) REFERENCES post(id),
	FOREIGN KEY (pool) REFERENCES pool(id)
);

CREATE TABLE IF NOT EXISTS tag (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	name VARCHAR(255) NOT NULL UNIQUE,

	alias_for BIGINT UNSIGNED,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (alias_for) REFERENCES tag(id)
);

CREATE TABLE IF NOT EXISTS post_tag (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	post BIGINT UNSIGNED NOT NULL,
	tag BIGINT UNSIGNED NOT NULL,

	assigned_by BIGINT UNSIGNED NOT NULL,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

	UNIQUE(post, tag),
	FOREIGN KEY (post) REFERENCES post(id),
	FOREIGN KEY (tag) REFERENCES tag(id),
	FOREIGN KEY (assigned_by) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS vote (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	post BIGINT UNSIGNED NOT NULL,
	user BIGINT UNSIGNED NOT NULL,

	kind ENUM('up', 'down', 'favorite') NOT NULL,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (post) REFERENCES post(id),
	FOREIGN KEY (user) REFERENCES user(id)
);

INSERT INTO user (name, password, level)
VALUES ('crawler', '-', 'bot');

-- migrate:down
DROP TABLE vote;
DROP TABLE post_tag;
DROP TABLE tag;
DROP TABLE pool_post;
DROP TABLE pool;
DROP TABLE post;
DROP TABLE post_crawl_info;
DROP TABLE user;
